# Use an official Nginx image as a base image
FROM nginx:latest

# Set the working directory to /app
WORKDIR /app

# Copy the PHP files into the container
COPY frontend/ /app

# Copy the Nginx configuration file
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Expose port 80 to the outside world
EXPOSE 80

# Define environment variable