# Use the official tiangolo/uvicorn-gunicorn-fastapi image as a parent image
FROM tiangolo/uvicorn-gunicorn-fastapi:latest

# Links Docker image with repository
LABEL org.opencontainers.image.source https://github.com/joaovitoriasilva/gearguardian

# Set the working directory
WORKDIR /app

# Install pkg-config
RUN apt-get update && apt-get install -y pkg-config python3-dev default-libmysqlclient-dev build-essential

# Copy the directory backend contents and requirements.txt file into the container at /app
COPY backend/ /app
COPY requirements.txt /app

# Create a virtual environment and install dependencies
RUN python -m venv /venv
ENV PATH=/venv/bin:$PATH
# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Make port 8000 available to the world outside this container
#EXPOSE 8000

# Define environment variable
ENV DB_HOST=""
ENV DB_PORT=3306
ENV DB_USER=""
ENV DB_PASSWORD=""
ENV DB_DATABASE=""
ENV SECRET_KEY=""
ENV ALGORITHM="HS256"
ENV ACCESS_TOKEN_EXPIRE_MINUTES=30
ENV STRAVA_CLIENT_ID=""
ENV STRAVA_CLIENT_SECRET=""
ENV STRAVA_AUTH_CODE=""
ENV JAEGER_HOST=""
ENV STRAVA_DAYS_ACTIVITIES_ONLINK=30

# Run app.py when the container launches
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
