"""Added additional columns to activities table

Revision ID: 24e2676546b1
Revises: ab815ee3beae
Create Date: 2024-09-17 15:41:59.800993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '24e2676546b1'
down_revision: Union[str, None] = 'ab815ee3beae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activities', sa.Column('max_speed', sa.DECIMAL(precision=20, scale=10), nullable=True, comment='Max speed seconds per meter (s/m)'))
    op.add_column('activities', sa.Column('max_power', sa.Integer(), nullable=True, comment='Max power (watts)'))
    op.add_column('activities', sa.Column('normalized_power', sa.Integer(), nullable=True, comment='Normalized power (watts)'))
    op.add_column('activities', sa.Column('average_hr', sa.Integer(), nullable=True, comment='Average heart rate (bpm)'))
    op.add_column('activities', sa.Column('max_hr', sa.Integer(), nullable=True, comment='Max heart rate (bpm)'))
    op.add_column('activities', sa.Column('average_cad', sa.Integer(), nullable=True, comment='Average cadence (rpm)'))
    op.add_column('activities', sa.Column('max_cad', sa.Integer(), nullable=True, comment='Max cadence (rpm)'))
    op.alter_column('activities', 'elevation_gain',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True,
               existing_comment='Elevation gain in meters')
    op.alter_column('activities', 'elevation_loss',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True,
               existing_comment='Elevation loss in meters')
    op.alter_column('activities', 'pace',
               existing_type=mysql.DECIMAL(precision=20, scale=10),
               nullable=True,
               existing_comment='Pace seconds per meter (s/m)')
    op.alter_column('activities', 'average_speed',
               existing_type=mysql.DECIMAL(precision=20, scale=10),
               nullable=True,
               existing_comment='Average speed seconds per meter (s/m)')
    op.alter_column('activities', 'average_power',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True,
               existing_comment='Average power (watts)')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('activities', 'average_power',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False,
               existing_comment='Average power (watts)')
    op.alter_column('activities', 'average_speed',
               existing_type=mysql.DECIMAL(precision=20, scale=10),
               nullable=False,
               existing_comment='Average speed seconds per meter (s/m)')
    op.alter_column('activities', 'pace',
               existing_type=mysql.DECIMAL(precision=20, scale=10),
               nullable=False,
               existing_comment='Pace seconds per meter (s/m)')
    op.alter_column('activities', 'elevation_loss',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False,
               existing_comment='Elevation loss in meters')
    op.alter_column('activities', 'elevation_gain',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False,
               existing_comment='Elevation gain in meters')
    op.drop_column('activities', 'max_cad')
    op.drop_column('activities', 'average_cad')
    op.drop_column('activities', 'max_hr')
    op.drop_column('activities', 'average_hr')
    op.drop_column('activities', 'normalized_power')
    op.drop_column('activities', 'max_power')
    op.drop_column('activities', 'max_speed')
    # ### end Alembic commands ###
