"""v0.7.0

Revision ID: 446a199ddd37
Revises: 542605083c0c
Create Date: 2024-12-26 21:43:01.958551

"""
from typing import Sequence, Union

from alembic import op
from sqlalchemy.engine.reflection import Inspector
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '446a199ddd37'
down_revision: Union[str, None] = '542605083c0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Get database connection and inspect constraints
    conn = op.get_bind()
    inspector = Inspector.from_engine(conn)

    # Get the list of indexes on the 'activities' table
    indexes = inspector.get_indexes('activities')

    # Check if the target index exists
    index_name = 'activities_garminconnect_activity_id_key'
    index_exists = any(index['name'] == index_name for index in indexes)

    if index_exists:
        # Drop the index if it exists
        op.drop_index(index_name, table_name='activities')

    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.VARCHAR(length=250),
               existing_comment='User password (hash)',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(length=250),
               type_=sa.VARCHAR(length=100),
               existing_comment='User password (hash)',
               existing_nullable=False)
    op.create_unique_constraint('activities_garminconnect_activity_id_key', 'activities', ['garminconnect_activity_id'])
    # ### end Alembic commands ###
