"""v0.10.0 migration

Revision ID: 4ac2cc4f4e41
Revises: 7217cc0eee8c
Create Date: 2025-02-27 15:43:18.729569

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "4ac2cc4f4e41"
down_revision: Union[str, None] = "7217cc0eee8c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "default_activity_visibility",
            sa.Integer(),
            nullable=False,
            server_default=sa.text("0"),
            comment="0 - public, 1 - followers, 2 - private",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "default_activity_visibility")
    # ### end Alembic commands ###
