"""v0.6.5 migration

Revision ID: 7ba9b71fe203
Revises: 65a0f1d72997
Create Date: 2024-11-25 13:07:30.142799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ba9b71fe203'
down_revision: Union[str, None] = '65a0f1d72997'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gear', sa.Column('initial_kms', sa.DECIMAL(precision=11, scale=3), nullable=False, comment='Initial kilometers of the gear'))
    op.alter_column('activities', 'start_time',
               existing_type=sa.DATETIME(),
               type_=sa.TIMESTAMP(),
               comment='Activity start date (TIMESTAMP)',
               existing_comment='Activity start date (datetime)',
               existing_nullable=False)
    op.alter_column('activities', 'end_time',
               existing_type=sa.DATETIME(),
               type_=sa.TIMESTAMP(),
               comment='Activity end date (TIMESTAMP)',
               existing_comment='Activity end date (datetime)',
               existing_nullable=False)
    op.alter_column('activities', 'total_elapsed_time',
               existing_type=sa.DECIMAL(precision=20, scale=10),
               comment='Activity total elapsed time (s)',
               existing_comment='Activity total elapsed time (datetime)',
               existing_nullable=False)
    op.alter_column('activities', 'total_timer_time',
               existing_type=sa.DECIMAL(precision=20, scale=10),
               comment='Activity total timer time (s)',
               existing_comment='Activity total timer time (datetime)',
               existing_nullable=False)
    op.alter_column('activities', 'created_at',
               existing_type=sa.DATETIME(),
               type_=sa.TIMESTAMP(),
               comment='Activity creation date (TIMESTAMP)',
               existing_comment='Activity creation date (datetime)',
               existing_nullable=False)
    op.alter_column('gear', 'created_at',
               existing_type=sa.DATETIME(),
               type_=sa.TIMESTAMP(),
               comment='Gear creation date (TIMESTAMP)',
               existing_comment='Gear creation date (date)',
               existing_nullable=False)
    op.add_column('health_data', sa.Column('bmi', sa.DECIMAL(precision=10, scale=2), nullable=True, comment='Body mass index (BMI)'))
    op.add_column('health_data', sa.Column('body_fat', sa.DECIMAL(precision=10, scale=2), nullable=True, comment='Body fat percentage'))
    op.add_column('health_data', sa.Column('body_water', sa.DECIMAL(precision=10, scale=2), nullable=True, comment='Body hydration percentage'))
    op.add_column('health_data', sa.Column('bone_mass', sa.DECIMAL(precision=10, scale=2), nullable=True, comment='Bone mass percentage'))
    op.add_column('health_data', sa.Column('muscle_mass', sa.DECIMAL(precision=10, scale=2), nullable=True, comment='Muscle mass percentage'))
    op.add_column('health_data', sa.Column('physique_rating', sa.DECIMAL(precision=10, scale=2), nullable=True, comment='Physique rating'))
    op.add_column('health_data', sa.Column('visceral_fat', sa.DECIMAL(precision=10, scale=2), nullable=True, comment='Visceral fat rating'))
    op.add_column('health_data', sa.Column('metabolic_age', sa.DECIMAL(precision=10, scale=2), nullable=True, comment='Metabolic age'))
    op.add_column('health_data', sa.Column('garminconnect_body_composition_id', sa.String(length=45), nullable=True, comment='Garmin Connect body composition ID'))
    op.alter_column('health_data', 'created_at',
               existing_type=sa.DATE(),
               comment='Health data creation date (date)',
               existing_comment='Health data creation date (datetime)',
               existing_nullable=False)
    op.add_column('activities', sa.Column('timezone', sa.String(length=250), nullable=True, comment='Activity timezone (May include spaces)'))
    op.execute("""
    INSERT INTO migrations (id, name, description, executed) VALUES
    (2, 'v0.6.5', 'Process timezone for existing activities', false);
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gear', 'initial_kms')
    op.alter_column('health_data', 'created_at',
               existing_type=sa.DATE(),
               comment='Health data creation date (datetime)',
               existing_comment='Health data creation date (date)',
               existing_nullable=False)
    op.drop_column('health_data', 'garminconnect_body_composition_id')
    op.drop_column('health_data', 'metabolic_age')
    op.drop_column('health_data', 'visceral_fat')
    op.drop_column('health_data', 'physique_rating')
    op.drop_column('health_data', 'muscle_mass')
    op.drop_column('health_data', 'bone_mass')
    op.drop_column('health_data', 'body_water')
    op.drop_column('health_data', 'body_fat')
    op.drop_column('health_data', 'bmi')
    op.alter_column('gear', 'created_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DATETIME(),
               comment='Gear creation date (date)',
               existing_comment='Gear creation date (TIMESTAMP)',
               existing_nullable=False)
    op.alter_column('activities', 'created_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DATETIME(),
               comment='Activity creation date (datetime)',
               existing_comment='Activity creation date (TIMESTAMP)',
               existing_nullable=False)
    op.alter_column('activities', 'total_timer_time',
               existing_type=sa.DECIMAL(precision=20, scale=10),
               comment='Activity total timer time (datetime)',
               existing_comment='Activity total timer time (s)',
               existing_nullable=False)
    op.alter_column('activities', 'total_elapsed_time',
               existing_type=sa.DECIMAL(precision=20, scale=10),
               comment='Activity total elapsed time (datetime)',
               existing_comment='Activity total elapsed time (s)',
               existing_nullable=False)
    op.alter_column('activities', 'end_time',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DATETIME(),
               comment='Activity end date (datetime)',
               existing_comment='Activity end date (TIMESTAMP)',
               existing_nullable=False)
    op.alter_column('activities', 'start_time',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DATETIME(),
               comment='Activity start date (datetime)',
               existing_comment='Activity start date (TIMESTAMP)',
               existing_nullable=False)
    op.drop_column('activities', 'timezone')
    op.execute("""
    DELETE FROM migrations 
    WHERE id = 2;
    """)
    # ### end Alembic commands ###
