"""your_migration_message

Revision ID: 9ca353e5d874
Revises: 2af2c0629b37
Create Date: 2025-11-24 14:47:35.920652

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9ca353e5d874"
down_revision: Union[str, None] = "2af2c0629b37"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "health_weight",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "user_id",
            sa.Integer(),
            nullable=False,
            comment="User ID that the health_data belongs",
        ),
        sa.Column(
            "date",
            sa.Date(),
            nullable=False,
            comment="Health data creation date (date)",
        ),
        sa.Column(
            "weight",
            sa.DECIMAL(precision=10, scale=2),
            nullable=True,
            comment="Weight in kg",
        ),
        sa.Column(
            "bmi",
            sa.DECIMAL(precision=10, scale=2),
            nullable=True,
            comment="Body mass index (BMI)",
        ),
        sa.Column(
            "body_fat",
            sa.DECIMAL(precision=10, scale=2),
            nullable=True,
            comment="Body fat percentage",
        ),
        sa.Column(
            "body_water",
            sa.DECIMAL(precision=10, scale=2),
            nullable=True,
            comment="Body hydration percentage",
        ),
        sa.Column(
            "bone_mass",
            sa.DECIMAL(precision=10, scale=2),
            nullable=True,
            comment="Bone mass percentage",
        ),
        sa.Column(
            "muscle_mass",
            sa.DECIMAL(precision=10, scale=2),
            nullable=True,
            comment="Muscle mass percentage",
        ),
        sa.Column(
            "physique_rating", sa.Integer(), nullable=True, comment="Physique rating"
        ),
        sa.Column(
            "visceral_fat",
            sa.DECIMAL(precision=10, scale=2),
            nullable=True,
            comment="Visceral fat rating",
        ),
        sa.Column(
            "metabolic_age", sa.Integer(), nullable=True, comment="Metabolic age"
        ),
        sa.Column(
            "garminconnect_body_composition_id",
            sa.String(length=45),
            nullable=True,
            comment="Garmin Connect body composition ID",
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_health_weight_user_id"), "health_weight", ["user_id"], unique=False
    )

    # Copy data from health_data to health_weight
    connection = op.get_bind()
    connection.execute(
        sa.text(
            """
        INSERT INTO health_weight (
            user_id, date, weight, bmi, garminconnect_body_composition_id,
            body_fat, body_water, bone_mass, muscle_mass, 
            physique_rating, visceral_fat, metabolic_age
        )
        SELECT 
            user_id, date, weight, bmi, garminconnect_body_composition_id,
            NULL as body_fat, NULL as body_water, NULL as bone_mass, NULL as muscle_mass,
            NULL as physique_rating, NULL as visceral_fat, NULL as metabolic_age
        FROM health_data
    """
        )
    )

    op.drop_index(op.f("ix_health_data_user_id"), table_name="health_data")
    op.drop_table("health_data")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "health_data",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "user_id",
            sa.INTEGER(),
            autoincrement=False,
            nullable=False,
            comment="User ID that the health_data belongs",
        ),
        sa.Column(
            "weight",
            sa.NUMERIC(precision=10, scale=2),
            autoincrement=False,
            nullable=True,
            comment="Weight in kg",
        ),
        sa.Column(
            "date",
            sa.DATE(),
            autoincrement=False,
            nullable=False,
            comment="Health data creation date (date)",
        ),
        sa.Column(
            "bmi",
            sa.NUMERIC(precision=10, scale=2),
            autoincrement=False,
            nullable=True,
            comment="Body mass index (BMI)",
        ),
        sa.Column(
            "garminconnect_body_composition_id",
            sa.VARCHAR(length=45),
            autoincrement=False,
            nullable=True,
            comment="Garmin Connect body composition ID",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("health_data_user_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("health_data_pkey")),
    )
    op.create_index(
        op.f("ix_health_data_user_id"), "health_data", ["user_id"], unique=False
    )

    # Copy data from health_weight back to health_data
    connection = op.get_bind()
    connection.execute(
        sa.text(
            """
        INSERT INTO health_data (
            user_id, date, weight, bmi, garminconnect_body_composition_id
        )
        SELECT 
            user_id, date, weight, bmi, garminconnect_body_composition_id
        FROM health_weight
    """
        )
    )

    op.drop_index(op.f("ix_health_weight_user_id"), table_name="health_weight")
    op.drop_table("health_weight")
    # ### end Alembic commands ###
