"""Changed gears and activities columns from DateTime to Timestamp and added additional body composition columns to health_data table

Revision ID: c03889875128
Revises: 7ba9b71fe203
Create Date: 2024-11-26 12:44:45.220803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c03889875128'
down_revision: Union[str, None] = '7ba9b71fe203'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('activities', 'start_time',
               existing_type=mysql.DATETIME(),
               type_=sa.TIMESTAMP(),
               comment='Activity start date (TIMESTAMP)',
               existing_comment='Activity start date (datetime)',
               existing_nullable=False)
    op.alter_column('activities', 'end_time',
               existing_type=mysql.DATETIME(),
               type_=sa.TIMESTAMP(),
               comment='Activity end date (TIMESTAMP)',
               existing_comment='Activity end date (datetime)',
               existing_nullable=False)
    op.alter_column('activities', 'total_elapsed_time',
               existing_type=mysql.DECIMAL(precision=20, scale=10),
               comment='Activity total elapsed time (s)',
               existing_comment='Activity total elapsed time (datetime)',
               existing_nullable=False)
    op.alter_column('activities', 'total_timer_time',
               existing_type=mysql.DECIMAL(precision=20, scale=10),
               comment='Activity total timer time (s)',
               existing_comment='Activity total timer time (datetime)',
               existing_nullable=False)
    op.alter_column('activities', 'created_at',
               existing_type=mysql.DATETIME(),
               type_=sa.TIMESTAMP(),
               comment='Activity creation date (TIMESTAMP)',
               existing_comment='Activity creation date (datetime)',
               existing_nullable=False)
    op.alter_column('gear', 'created_at',
               existing_type=mysql.DATETIME(),
               type_=sa.TIMESTAMP(),
               comment='Gear creation date (TIMESTAMP)',
               existing_comment='Gear creation date (date)',
               existing_nullable=False)
    op.add_column('health_data', sa.Column('bmi', sa.DECIMAL(precision=10, scale=2), nullable=True, comment='Body mass index (BMI)'))
    op.add_column('health_data', sa.Column('body_fat', sa.DECIMAL(precision=10, scale=2), nullable=True, comment='Body fat percentage'))
    op.add_column('health_data', sa.Column('body_water', sa.DECIMAL(precision=10, scale=2), nullable=True, comment='Body hydration percentage'))
    op.add_column('health_data', sa.Column('bone_mass', sa.DECIMAL(precision=10, scale=2), nullable=True, comment='Bone mass percentage'))
    op.add_column('health_data', sa.Column('muscle_mass', sa.DECIMAL(precision=10, scale=2), nullable=True, comment='Muscle mass percentage'))
    op.add_column('health_data', sa.Column('physique_rating', sa.DECIMAL(precision=10, scale=2), nullable=True, comment='Physique rating'))
    op.add_column('health_data', sa.Column('visceral_fat', sa.DECIMAL(precision=10, scale=2), nullable=True, comment='Visceral fat rating'))
    op.add_column('health_data', sa.Column('metabolic_age', sa.DECIMAL(precision=10, scale=2), nullable=True, comment='Metabolic age'))
    op.add_column('health_data', sa.Column('garminconnect_body_composition_id', sa.String(length=45), nullable=True, comment='Garmin Connect body composition ID'))
    op.alter_column('health_data', 'created_at',
               existing_type=sa.DATE(),
               comment='Health data creation date (date)',
               existing_comment='Health data creation date (datetime)',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('health_data', 'created_at',
               existing_type=sa.DATE(),
               comment='Health data creation date (datetime)',
               existing_comment='Health data creation date (date)',
               existing_nullable=False)
    op.drop_column('health_data', 'garminconnect_body_composition_id')
    op.drop_column('health_data', 'metabolic_age')
    op.drop_column('health_data', 'visceral_fat')
    op.drop_column('health_data', 'physique_rating')
    op.drop_column('health_data', 'muscle_mass')
    op.drop_column('health_data', 'bone_mass')
    op.drop_column('health_data', 'body_water')
    op.drop_column('health_data', 'body_fat')
    op.drop_column('health_data', 'bmi')
    op.alter_column('gear', 'created_at',
               existing_type=sa.TIMESTAMP(),
               type_=mysql.DATETIME(),
               comment='Gear creation date (date)',
               existing_comment='Gear creation date (TIMESTAMP)',
               existing_nullable=False)
    op.alter_column('activities', 'created_at',
               existing_type=sa.TIMESTAMP(),
               type_=mysql.DATETIME(),
               comment='Activity creation date (datetime)',
               existing_comment='Activity creation date (TIMESTAMP)',
               existing_nullable=False)
    op.alter_column('activities', 'total_timer_time',
               existing_type=mysql.DECIMAL(precision=20, scale=10),
               comment='Activity total timer time (datetime)',
               existing_comment='Activity total timer time (s)',
               existing_nullable=False)
    op.alter_column('activities', 'total_elapsed_time',
               existing_type=mysql.DECIMAL(precision=20, scale=10),
               comment='Activity total elapsed time (datetime)',
               existing_comment='Activity total elapsed time (s)',
               existing_nullable=False)
    op.alter_column('activities', 'end_time',
               existing_type=sa.TIMESTAMP(),
               type_=mysql.DATETIME(),
               comment='Activity end date (datetime)',
               existing_comment='Activity end date (TIMESTAMP)',
               existing_nullable=False)
    op.alter_column('activities', 'start_time',
               existing_type=sa.TIMESTAMP(),
               type_=mysql.DATETIME(),
               comment='Activity start date (datetime)',
               existing_comment='Activity start date (TIMESTAMP)',
               existing_nullable=False)
    # ### end Alembic commands ###
