"""Added new table health_data and add new height column to user table

Revision ID: ccfd790687f5
Revises: 785b0116a643
Create Date: 2024-09-22 12:55:48.863891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ccfd790687f5'
down_revision: Union[str, None] = '785b0116a643'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('health_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='User ID that the health_data belongs'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Health data creation date (datetime)'),
    sa.Column('weight', sa.DECIMAL(precision=10, scale=2), nullable=True, comment='Weight in kg'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('created_at')
    )
    op.create_index(op.f('ix_health_data_user_id'), 'health_data', ['user_id'], unique=False)
    op.add_column('users', sa.Column('height', sa.Integer(), nullable=True, comment='User height in centimeters'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'height')
    op.drop_index(op.f('ix_health_data_user_id'), table_name='health_data')
    op.drop_table('health_data')
    # ### end Alembic commands ###
