"""v0.16.0 migration health steps

Revision ID: 9ce568f3bce0
Revises: 9ca353e5d874
Create Date: 2025-11-24 16:14:09.794492

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9ce568f3bce0"
down_revision: Union[str, None] = "9ca353e5d874"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "health_steps",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "user_id",
            sa.Integer(),
            nullable=False,
            comment="User ID that the health_steps belongs",
        ),
        sa.Column(
            "date", sa.Date(), nullable=False, comment="Health steps date (date)"
        ),
        sa.Column(
            "steps", sa.Integer(), nullable=False, comment="Number of steps taken"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_health_steps_user_id"), "health_steps", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_health_steps_user_id"), table_name="health_steps")
    op.drop_table("health_steps")
    # ### end Alembic commands ###
