"""v0.16.0 migration

Revision ID: 2af2c0629b37
Revises: 3c4d5e6f7a8b
Create Date: 2025-10-05 22:47:48.949687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2af2c0629b37'
down_revision: Union[str, None] = '3c4d5e6f7a8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_sign_up_tokens_user_id'), 'sign_up_tokens', ['user_id'], unique=False)
    
    # Delete all existing sessions before altering the refresh_token column
    op.execute('DELETE FROM users_sessions')
    # Alter the refresh_token column to be shorter and to reflect that it is hashed
    op.alter_column('users_sessions', 'refresh_token',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=255),
               comment='Session hashed refresh token',
               existing_comment='Session refresh token',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users_sessions', 'refresh_token',
            existing_type=sa.String(length=255),
            type_=sa.VARCHAR(length=500),
            comment='Session refresh token',
            existing_comment='Session hashed refresh token',
            existing_nullable=False)
    op.drop_index(op.f('ix_sign_up_tokens_user_id'), table_name='sign_up_tokens')
    # ### end Alembic commands ###
