"""v0.16.0 migration health_sleep

Revision ID: 4c6af41fffa0
Revises: 2af2c0629b37
Create Date: 2025-11-25 16:25:56.221138

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4c6af41fffa0"
down_revision: Union[str, None] = "2af2c0629b37"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "health_sleep",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "user_id",
            sa.Integer(),
            nullable=False,
            comment="User ID that the health_sleep belongs",
        ),
        sa.Column(
            "date",
            sa.Date(),
            nullable=False,
            comment="Calendar date of the sleep session",
        ),
        sa.Column(
            "sleep_start_time_gmt",
            sa.DateTime(),
            nullable=True,
            comment="Start time of sleep in GMT",
        ),
        sa.Column(
            "sleep_end_time_gmt",
            sa.DateTime(),
            nullable=True,
            comment="End time of sleep in GMT",
        ),
        sa.Column(
            "sleep_start_time_local",
            sa.DateTime(),
            nullable=True,
            comment="Start time of sleep in local time",
        ),
        sa.Column(
            "sleep_end_time_local",
            sa.DateTime(),
            nullable=True,
            comment="End time of sleep in local time",
        ),
        sa.Column(
            "total_sleep_seconds",
            sa.Integer(),
            nullable=True,
            comment="Total duration of sleep in seconds",
        ),
        sa.Column(
            "nap_time_seconds",
            sa.Integer(),
            nullable=True,
            comment="Duration of naps in seconds",
        ),
        sa.Column(
            "unmeasurable_sleep_seconds",
            sa.Integer(),
            nullable=True,
            comment="Unmeasurable sleep duration in seconds",
        ),
        sa.Column(
            "deep_sleep_seconds",
            sa.Integer(),
            nullable=True,
            comment="Duration of deep sleep in seconds",
        ),
        sa.Column(
            "light_sleep_seconds",
            sa.Integer(),
            nullable=True,
            comment="Duration of light sleep in seconds",
        ),
        sa.Column(
            "rem_sleep_seconds",
            sa.Integer(),
            nullable=True,
            comment="Duration of REM sleep in seconds",
        ),
        sa.Column(
            "awake_sleep_seconds",
            sa.Integer(),
            nullable=True,
            comment="Duration of awake time in seconds",
        ),
        sa.Column(
            "avg_heart_rate",
            sa.DECIMAL(precision=10, scale=2),
            nullable=True,
            comment="Average heart rate during sleep",
        ),
        sa.Column(
            "min_heart_rate",
            sa.Integer(),
            nullable=True,
            comment="Minimum heart rate during sleep",
        ),
        sa.Column(
            "max_heart_rate",
            sa.Integer(),
            nullable=True,
            comment="Maximum heart rate during sleep",
        ),
        sa.Column(
            "avg_spo2",
            sa.DECIMAL(precision=10, scale=2),
            nullable=True,
            comment="Average SpO2 oxygen saturation percentage",
        ),
        sa.Column(
            "lowest_spo2",
            sa.Integer(),
            nullable=True,
            comment="Lowest SpO2 reading during sleep",
        ),
        sa.Column(
            "highest_spo2",
            sa.Integer(),
            nullable=True,
            comment="Highest SpO2 reading during sleep",
        ),
        sa.Column(
            "avg_respiration",
            sa.DECIMAL(precision=10, scale=2),
            nullable=True,
            comment="Average respiration rate",
        ),
        sa.Column(
            "lowest_respiration",
            sa.DECIMAL(precision=10, scale=2),
            nullable=True,
            comment="Lowest respiration rate",
        ),
        sa.Column(
            "highest_respiration",
            sa.DECIMAL(precision=10, scale=2),
            nullable=True,
            comment="Highest respiration rate",
        ),
        sa.Column(
            "avg_stress_level",
            sa.DECIMAL(precision=10, scale=2),
            nullable=True,
            comment="Average stress level during sleep",
        ),
        sa.Column(
            "awake_count",
            sa.Integer(),
            nullable=True,
            comment="Number of times awakened during sleep",
        ),
        sa.Column(
            "restless_moments_count",
            sa.Integer(),
            nullable=True,
            comment="Count of restless moments",
        ),
        sa.Column(
            "sleep_score_overall",
            sa.Integer(),
            nullable=True,
            comment="Overall sleep score (0-100)",
        ),
        sa.Column(
            "sleep_score_duration",
            sa.String(length=50),
            nullable=True,
            comment="Sleep duration score (e.g., GOOD, EXCELLENT, POOR)",
        ),
        sa.Column(
            "sleep_score_quality",
            sa.String(length=50),
            nullable=True,
            comment="Sleep quality score",
        ),
        sa.Column(
            "garminconnect_sleep_id",
            sa.String(length=250),
            nullable=True,
            comment="External Garmin Connect sleep ID",
        ),
        sa.Column(
            "sleep_stages",
            sa.JSON(),
            nullable=True,
            comment="List of sleep stage intervals as JSON",
        ),
        sa.Column(
            "source",
            sa.String(length=250),
            nullable=True,
            comment="Source of the health sleep data",
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_health_sleep_date"), "health_sleep", ["date"], unique=False
    )
    op.create_index(
        op.f("ix_health_sleep_user_id"), "health_sleep", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_health_sleep_user_id"), table_name="health_sleep")
    op.drop_index(op.f("ix_health_sleep_date"), table_name="health_sleep")
    op.drop_table("health_sleep")
    # ### end Alembic commands ###
