"""v0.16.0 migration

Revision ID: 2af2c0629b37
Revises: 3c4d5e6f7a8b
Create Date: 2025-10-05 22:47:48.949687

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2af2c0629b37"
down_revision: Union[str, None] = "3c4d5e6f7a8b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Delete all existing sessions before altering the refresh_token column
    op.execute("DELETE FROM users_sessions")
    # Alter the refresh_token column to be shorter and to reflect that it is hashed
    op.alter_column(
        "users_sessions",
        "refresh_token",
        existing_type=sa.VARCHAR(length=500),
        type_=sa.String(length=255),
        comment="Session hashed refresh token",
        existing_comment="Session refresh token",
        existing_nullable=False,
    )

    # Create table identity_providers
    op.create_table(
        "identity_providers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "name",
            sa.String(length=100),
            nullable=False,
            comment="Display name of the IdP",
        ),
        sa.Column(
            "slug", sa.String(length=50), nullable=False, comment="URL-safe identifier"
        ),
        sa.Column(
            "provider_type",
            sa.String(length=50),
            nullable=False,
            comment="Type: oidc, oauth2, saml",
        ),
        sa.Column(
            "enabled",
            sa.Boolean(),
            nullable=False,
            comment="Whether this provider is enabled",
        ),
        sa.Column(
            "client_id",
            sa.String(length=512),
            nullable=True,
            comment="OAuth2/OIDC client ID (encrypted)",
        ),
        sa.Column(
            "client_secret",
            sa.String(length=512),
            nullable=True,
            comment="OAuth2/OIDC client secret (encrypted)",
        ),
        sa.Column(
            "issuer_url",
            sa.String(length=500),
            nullable=True,
            comment="OIDC issuer/discovery URL",
        ),
        sa.Column(
            "authorization_endpoint",
            sa.String(length=500),
            nullable=True,
            comment="OAuth2/OIDC authorization endpoint",
        ),
        sa.Column(
            "token_endpoint",
            sa.String(length=500),
            nullable=True,
            comment="OAuth2/OIDC token endpoint",
        ),
        sa.Column(
            "userinfo_endpoint",
            sa.String(length=500),
            nullable=True,
            comment="OIDC userinfo endpoint",
        ),
        sa.Column(
            "jwks_uri",
            sa.String(length=500),
            nullable=True,
            comment="OIDC JWKS URI for token verification",
        ),
        sa.Column(
            "scopes",
            sa.String(length=500),
            nullable=True,
            comment="OAuth2/OIDC scopes to request",
        ),
        sa.Column(
            "icon",
            sa.String(length=100),
            nullable=True,
            comment="Icon name (FontAwesome) or custom URL",
        ),
        sa.Column(
            "auto_create_users",
            sa.Boolean(),
            nullable=False,
            comment="Automatically create users on first login",
        ),
        sa.Column(
            "sync_user_info",
            sa.Boolean(),
            nullable=False,
            comment="Sync user info on each login",
        ),
        sa.Column(
            "user_mapping",
            sa.JSON(),
            nullable=True,
            comment="JSON mapping of IdP claims to user fields",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="When this provider was created",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="When this provider was last updated",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_identity_providers_enabled"),
        "identity_providers",
        ["enabled"],
        unique=False,
    )
    op.create_index(
        op.f("ix_identity_providers_id"), "identity_providers", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_identity_providers_slug"), "identity_providers", ["slug"], unique=True
    )

    # Create table users_identity_providers
    op.create_table(
        "users_identity_providers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False, comment="User ID"),
        sa.Column(
            "idp_id", sa.Integer(), nullable=False, comment="Identity Provider ID"
        ),
        sa.Column(
            "idp_subject",
            sa.String(length=500),
            nullable=False,
            comment="Subject/ID from the identity provider (unique per IdP)",
        ),
        sa.Column(
            "linked_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="When this IdP was linked to the user",
        ),
        sa.Column(
            "last_login",
            sa.DateTime(),
            nullable=True,
            comment="Last time user logged in with this IdP",
        ),
        sa.Column(
            "idp_refresh_token",
            sa.Text(),
            nullable=True,
            comment="Encrypted refresh token",
        ),
        sa.Column(
            "idp_access_token_expires_at",
            sa.DateTime(),
            nullable=True,
            comment="Access token expiry time",
        ),
        sa.Column(
            "idp_refresh_token_updated_at",
            sa.DateTime(),
            nullable=True,
            comment="Last refresh",
        ),
        sa.ForeignKeyConstraint(
            ["idp_id"], ["identity_providers.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_users_identity_providers_id"),
        "users_identity_providers",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_users_identity_providers_idp_id"),
        "users_identity_providers",
        ["idp_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_users_identity_providers_user_id"),
        "users_identity_providers",
        ["user_id"],
        unique=False,
    )

    # Add additional columns to server_settings
    op.add_column(
        "server_settings",
        sa.Column(
            "sso_enabled",
            sa.Boolean(),
            nullable=True,
            comment="Enable SSO/IdP login (true - yes, false - no)",
        ),
    )
    op.execute(
        """
        UPDATE server_settings
        SET sso_enabled = false
        WHERE sso_enabled IS NULL;
    """
    )
    op.alter_column(
        "server_settings",
        "sso_enabled",
        nullable=False,
        comment="Enable SSO/IdP login (true - yes, false - no)",
        existing_type=sa.Boolean(),
    )
    op.add_column(
        "server_settings",
        sa.Column(
            "local_login_enabled",
            sa.Boolean(),
            nullable=True,
            comment="Allow local username/password login (true - yes, false - no)",
        ),
    )
    op.execute(
        """
        UPDATE server_settings
        SET local_login_enabled = true
        WHERE local_login_enabled IS NULL;
    """
    )
    op.alter_column(
        "server_settings",
        "local_login_enabled",
        nullable=False,
        comment="Allow local username/password login (true - yes, false - no)",
        existing_type=sa.Boolean(),
    )
    op.add_column(
        "server_settings",
        sa.Column(
            "sso_auto_redirect",
            sa.Boolean(),
            nullable=True,
            comment="Auto-redirect to SSO if only one IdP (true - yes, false - no)",
        ),
    )
    op.execute(
        """
        UPDATE server_settings
        SET sso_auto_redirect = false
        WHERE sso_auto_redirect IS NULL;
    """
    )
    op.alter_column(
        "server_settings",
        "sso_auto_redirect",
        nullable=False,
        comment="Auto-redirect to SSO if only one IdP (true - yes, false - no)",
        existing_type=sa.Boolean(),
    )

    # Create table health_steps
    op.create_table(
        "health_steps",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "user_id",
            sa.Integer(),
            nullable=False,
            comment="User ID that the health_steps belongs",
        ),
        sa.Column(
            "date", sa.Date(), nullable=False, comment="Health steps date (date)"
        ),
        sa.Column(
            "steps", sa.Integer(), nullable=False, comment="Number of steps taken"
        ),
        sa.Column(
            "source",
            sa.String(length=250),
            nullable=True,
            comment="Source of the health steps data",
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_health_steps_user_id"), "health_steps", ["user_id"], unique=False
    )

    # Migrate data from health_data to health_weight
    op.create_table(
        "health_weight",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "user_id",
            sa.Integer(),
            nullable=False,
            comment="User ID that the health_weight belongs",
        ),
        sa.Column(
            "date",
            sa.Date(),
            nullable=False,
            comment="Health weight date (date)",
        ),
        sa.Column(
            "weight",
            sa.DECIMAL(precision=10, scale=2),
            nullable=False,
            comment="Weight in kg",
        ),
        sa.Column(
            "bmi",
            sa.DECIMAL(precision=10, scale=2),
            nullable=True,
            comment="Body mass index (BMI)",
        ),
        sa.Column(
            "body_fat",
            sa.DECIMAL(precision=10, scale=2),
            nullable=True,
            comment="Body fat percentage",
        ),
        sa.Column(
            "body_water",
            sa.DECIMAL(precision=10, scale=2),
            nullable=True,
            comment="Body hydration percentage",
        ),
        sa.Column(
            "bone_mass",
            sa.DECIMAL(precision=10, scale=2),
            nullable=True,
            comment="Bone mass percentage",
        ),
        sa.Column(
            "muscle_mass",
            sa.DECIMAL(precision=10, scale=2),
            nullable=True,
            comment="Muscle mass percentage",
        ),
        sa.Column(
            "physique_rating", sa.Integer(), nullable=True, comment="Physique rating"
        ),
        sa.Column(
            "visceral_fat",
            sa.DECIMAL(precision=10, scale=2),
            nullable=True,
            comment="Visceral fat rating",
        ),
        sa.Column(
            "metabolic_age", sa.Integer(), nullable=True, comment="Metabolic age"
        ),
        sa.Column(
            "source",
            sa.String(length=250),
            nullable=True,
            comment="Source of the health weight data",
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_health_weight_user_id"), "health_weight", ["user_id"], unique=False
    )

    # Copy data from health_data to health_weight
    connection = op.get_bind()
    connection.execute(
        sa.text(
            """
        INSERT INTO health_weight (
            user_id, date, weight, bmi, source,
            body_fat, body_water, bone_mass, muscle_mass, 
            physique_rating, visceral_fat, metabolic_age
        )
        SELECT 
            user_id, date, weight, bmi, garminconnect_body_composition_id,
            NULL as body_fat, NULL as body_water, NULL as bone_mass, NULL as muscle_mass,
            NULL as physique_rating, NULL as visceral_fat, NULL as metabolic_age
        FROM health_data
    """
        )
    )

    op.drop_index(op.f("ix_health_data_user_id"), table_name="health_data")
    op.drop_table("health_data")

    # Add steps column to health_targets
    op.add_column(
        "health_targets",
        sa.Column(
            "steps", sa.Integer(), nullable=True, comment="Number of steps taken"
        ),
    )
    op.add_column(
        "health_targets",
        sa.Column(
            "sleep",
            sa.Integer(),
            nullable=True,
            comment="Number of hours slept in seconds",
        ),
    )

    # Create table health_sleep
    op.create_table(
        "health_sleep",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "user_id",
            sa.Integer(),
            nullable=False,
            comment="User ID that the health_sleep belongs",
        ),
        sa.Column(
            "date",
            sa.Date(),
            nullable=False,
            comment="Calendar date of the sleep session",
        ),
        sa.Column(
            "sleep_start_time_gmt",
            sa.DateTime(),
            nullable=True,
            comment="Start time of sleep in GMT",
        ),
        sa.Column(
            "sleep_end_time_gmt",
            sa.DateTime(),
            nullable=True,
            comment="End time of sleep in GMT",
        ),
        sa.Column(
            "sleep_start_time_local",
            sa.DateTime(),
            nullable=True,
            comment="Start time of sleep in local time",
        ),
        sa.Column(
            "sleep_end_time_local",
            sa.DateTime(),
            nullable=True,
            comment="End time of sleep in local time",
        ),
        sa.Column(
            "total_sleep_seconds",
            sa.Integer(),
            nullable=True,
            comment="Total duration of sleep in seconds",
        ),
        sa.Column(
            "nap_time_seconds",
            sa.Integer(),
            nullable=True,
            comment="Duration of naps in seconds",
        ),
        sa.Column(
            "unmeasurable_sleep_seconds",
            sa.Integer(),
            nullable=True,
            comment="Unmeasurable sleep duration in seconds",
        ),
        sa.Column(
            "deep_sleep_seconds",
            sa.Integer(),
            nullable=True,
            comment="Duration of deep sleep in seconds",
        ),
        sa.Column(
            "light_sleep_seconds",
            sa.Integer(),
            nullable=True,
            comment="Duration of light sleep in seconds",
        ),
        sa.Column(
            "rem_sleep_seconds",
            sa.Integer(),
            nullable=True,
            comment="Duration of REM sleep in seconds",
        ),
        sa.Column(
            "awake_sleep_seconds",
            sa.Integer(),
            nullable=True,
            comment="Duration of awake time in seconds",
        ),
        sa.Column(
            "avg_heart_rate",
            sa.Integer(),
            nullable=True,
            comment="Average heart rate during sleep",
        ),
        sa.Column(
            "min_heart_rate",
            sa.Integer(),
            nullable=True,
            comment="Minimum heart rate during sleep",
        ),
        sa.Column(
            "max_heart_rate",
            sa.Integer(),
            nullable=True,
            comment="Maximum heart rate during sleep",
        ),
        sa.Column(
            "avg_spo2",
            sa.Integer(),
            nullable=True,
            comment="Average SpO2 oxygen saturation percentage",
        ),
        sa.Column(
            "lowest_spo2",
            sa.Integer(),
            nullable=True,
            comment="Lowest SpO2 reading during sleep",
        ),
        sa.Column(
            "highest_spo2",
            sa.Integer(),
            nullable=True,
            comment="Highest SpO2 reading during sleep",
        ),
        sa.Column(
            "avg_respiration",
            sa.Integer(),
            nullable=True,
            comment="Average respiration rate",
        ),
        sa.Column(
            "lowest_respiration",
            sa.Integer(),
            nullable=True,
            comment="Lowest respiration rate",
        ),
        sa.Column(
            "highest_respiration",
            sa.Integer(),
            nullable=True,
            comment="Highest respiration rate",
        ),
        sa.Column(
            "avg_stress_level",
            sa.Integer(),
            nullable=True,
            comment="Average stress level during sleep",
        ),
        sa.Column(
            "awake_count",
            sa.Integer(),
            nullable=True,
            comment="Number of times awakened during sleep",
        ),
        sa.Column(
            "restless_moments_count",
            sa.Integer(),
            nullable=True,
            comment="Count of restless moments",
        ),
        sa.Column(
            "sleep_score_overall",
            sa.Integer(),
            nullable=True,
            comment="Overall sleep score (0-100)",
        ),
        sa.Column(
            "sleep_score_duration",
            sa.String(length=50),
            nullable=True,
            comment="Sleep duration score (e.g., GOOD, EXCELLENT, POOR)",
        ),
        sa.Column(
            "sleep_score_quality",
            sa.String(length=50),
            nullable=True,
            comment="Sleep quality score",
        ),
        sa.Column(
            "garminconnect_sleep_id",
            sa.String(length=250),
            nullable=True,
            comment="External Garmin Connect sleep ID",
        ),
        sa.Column(
            "sleep_stages",
            sa.JSON(),
            nullable=True,
            comment="List of sleep stage intervals as JSON",
        ),
        sa.Column(
            "source",
            sa.String(length=250),
            nullable=True,
            comment="Source of the health sleep data",
        ),
        sa.Column(
            "hrv_status",
            sa.String(length=50),
            nullable=True,
            comment="Heart rate variability status",
        ),
        sa.Column(
            "resting_heart_rate",
            sa.Integer(),
            nullable=True,
            comment="Resting heart rate during sleep",
        ),
        sa.Column(
            "avg_skin_temp_deviation",
            sa.DECIMAL(precision=10, scale=2),
            nullable=True,
            comment="Average skin temperature deviation during sleep in Celsius",
        ),
        sa.Column(
            "awake_count_score",
            sa.String(length=50),
            nullable=True,
            comment="Awake count score",
        ),
        sa.Column(
            "rem_percentage_score",
            sa.String(length=50),
            nullable=True,
            comment="REM sleep percentage score",
        ),
        sa.Column(
            "deep_percentage_score",
            sa.String(length=50),
            nullable=True,
            comment="Deep sleep percentage score",
        ),
        sa.Column(
            "light_percentage_score",
            sa.String(length=50),
            nullable=True,
            comment="Light sleep percentage score",
        ),
        sa.Column(
            "avg_sleep_stress",
            sa.Integer(),
            nullable=True,
            comment="Average sleep stress level",
        ),
        sa.Column(
            "sleep_stress_score",
            sa.String(length=50),
            nullable=True,
            comment="Sleep stress score",
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_health_sleep_date"), "health_sleep", ["date"], unique=False
    )
    op.create_index(
        op.f("ix_health_sleep_user_id"), "health_sleep", ["user_id"], unique=False
    )

    # Add max_heart_rate column to users table
    op.add_column(
        "users",
        sa.Column(
            "max_heart_rate",
            sa.Integer(),
            nullable=True,
            comment="User maximum heart rate (bpm)",
        ),
    )

    # Update health_weight source column to "garmin" where not null
    connection.execute(
        sa.text(
            """
        UPDATE health_weight
        SET source = 'garmin'
        WHERE source IS NOT NULL
    """
        )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove max_heart_rate column from users table
    op.drop_column("users", "max_heart_rate")

    # Drop table health_sleep
    op.drop_index(op.f("ix_health_sleep_user_id"), table_name="health_sleep")
    op.drop_index(op.f("ix_health_sleep_date"), table_name="health_sleep")
    op.drop_table("health_sleep")

    # Remove steps column from health_targets
    op.drop_column("health_targets", "sleep")
    op.drop_column("health_targets", "steps")

    # Revert and migrate data from health_weight to health_data
    op.create_table(
        "health_data",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "user_id",
            sa.INTEGER(),
            autoincrement=False,
            nullable=False,
            comment="User ID that the health_data belongs",
        ),
        sa.Column(
            "weight",
            sa.NUMERIC(precision=10, scale=2),
            autoincrement=False,
            nullable=True,
            comment="Weight in kg",
        ),
        sa.Column(
            "date",
            sa.DATE(),
            autoincrement=False,
            nullable=False,
            comment="Health data creation date (date)",
        ),
        sa.Column(
            "bmi",
            sa.NUMERIC(precision=10, scale=2),
            autoincrement=False,
            nullable=True,
            comment="Body mass index (BMI)",
        ),
        sa.Column(
            "garminconnect_body_composition_id",
            sa.VARCHAR(length=45),
            autoincrement=False,
            nullable=True,
            comment="Garmin Connect body composition ID",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("health_data_user_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("health_data_pkey")),
    )
    op.create_index(
        op.f("ix_health_data_user_id"), "health_data", ["user_id"], unique=False
    )

    # Copy data from health_weight back to health_data
    connection = op.get_bind()
    connection.execute(
        sa.text(
            """
        INSERT INTO health_data (
            user_id, date, weight, bmi, garminconnect_body_composition_id
        )
        SELECT 
            user_id, date, weight, bmi, source
        FROM health_weight
    """
        )
    )

    op.drop_index(op.f("ix_health_weight_user_id"), table_name="health_weight")
    op.drop_table("health_weight")
    # Drop health_steps table
    op.drop_index(op.f("ix_health_steps_user_id"), table_name="health_steps")
    op.drop_table("health_steps")
    # Remove added columns from server_settings
    op.drop_column("server_settings", "sso_auto_redirect")
    op.drop_column("server_settings", "local_login_enabled")
    op.drop_column("server_settings", "sso_enabled")
    # Drop users_identity_providers table
    op.drop_index(
        op.f("ix_users_identity_providers_user_id"),
        table_name="users_identity_providers",
    )
    op.drop_index(
        op.f("ix_users_identity_providers_idp_id"),
        table_name="users_identity_providers",
    )
    op.drop_index(
        op.f("ix_users_identity_providers_id"),
        table_name="users_identity_providers",
    )
    op.drop_table("users_identity_providers")
    # Drop identity_providers table
    op.drop_index(op.f("ix_identity_providers_slug"), table_name="identity_providers")
    op.drop_index(op.f("ix_identity_providers_id"), table_name="identity_providers")
    op.drop_index(
        op.f("ix_identity_providers_enabled"), table_name="identity_providers"
    )
    op.drop_table("identity_providers")
    # Revert the refresh_token column alteration
    op.alter_column(
        "users_sessions",
        "refresh_token",
        existing_type=sa.String(length=255),
        type_=sa.VARCHAR(length=500),
        comment="Session refresh token",
        existing_comment="Session hashed refresh token",
        existing_nullable=False,
    )
    # ### end Alembic commands ###
