
export function getGearComponentType(type, t) {
	const avatarMap = {
		"back_tire": t("gearComponentListComponent.gearComponentBackTire"),
		"front_tire": t("gearComponentListComponent.gearComponentFrontTire"),
		"back_tube": t("gearComponentListComponent.gearComponentBackTube"),
		"front_tube": t("gearComponentListComponent.gearComponentFrontTube"),
		"back_wheel_valve": t("gearComponentListComponent.gearComponentBackWheelValve"),
		"front_wheel_valve": t("gearComponentListComponent.gearComponentFrontWheelValve"),
		"back_tubeless_sealant": t("gearComponentListComponent.gearComponentBackTubelessSealant"),
		"front_tubeless_sealant": t("gearComponentListComponent.gearComponentFrontTubelessSealant"),
		"back_wheel": t("gearComponentListComponent.gearComponentBackWheel"),
		"front_wheel": t("gearComponentListComponent.gearComponentFrontWheel"),
		"back_break_rotor": t("gearComponentListComponent.gearComponentBackBreakRotor"),
		"front_break_rotor": t("gearComponentListComponent.gearComponentFrontBreakRotor"),
		"back_break_pads": t("gearComponentListComponent.gearComponentBackBreakPads"),
		"front_break_pads": t("gearComponentListComponent.gearComponentFrontBreakPads"),
		"back_break_oil": t("gearComponentListComponent.gearComponentBackBreakOil"),
		"front_break_oil": t("gearComponentListComponent.gearComponentFrontBreakOil"),
		"crank_left_power_meter": t("gearComponentListComponent.gearComponentCrankLeftPowerMeter"),
		"crank_right_power_meter": t("gearComponentListComponent.gearComponentCrankRightPowerMeter"),
		"crankset_power_meter": t("gearComponentListComponent.gearComponentCranksetPowerMeter"),
		"pedals_left_power_meter": t("gearComponentListComponent.gearComponentPedalsLeftPowerMeter"),
		"pedals_right_power_meter": t("gearComponentListComponent.gearComponentPedalsRightPowerMeter"),
		"pedals_power_meter": t("gearComponentListComponent.gearComponentPedalsPowerMeter"),
		"pedals": t("gearComponentListComponent.gearComponentPedals"),
		"crankset": t("gearComponentListComponent.gearComponentCrankset"),
		"cassette": t("gearComponentListComponent.gearComponentCassette"),
		"chain": t("gearComponentListComponent.gearComponentChain"),
		"front_shifter": t("gearComponentListComponent.gearComponentFrontShifter"),
		"front_derailleur": t("gearComponentListComponent.gearComponentFrontDerailleur"),
		"rear_shifter": t("gearComponentListComponent.gearComponentRearShifter"),
		"rear_derailleur": t("gearComponentListComponent.gearComponentRearDerailleur"),
		"bottom_bracket": t("gearComponentListComponent.gearComponentBottomBracket"),
		"bottle_cage": t("gearComponentListComponent.gearComponentBottleCage"),
		"handlebar": t("gearComponentListComponent.gearComponentHandlebar"),
		"headset": t("gearComponentListComponent.gearComponentHeadset"),
		"computer_mount": t("gearComponentListComponent.gearComponentComputerMount"),
		"handlebar_tape": t("gearComponentListComponent.gearComponentHandlebarTape"),
		"grips": t("gearComponentListComponent.gearComponentGrips"),
		"stem": t("gearComponentListComponent.gearComponentStem"),
		"seatpost": t("gearComponentListComponent.gearComponentSeatpost"),
		"saddle": t("gearComponentListComponent.gearComponentSaddle"),
		"fork": t("gearComponentListComponent.gearComponentFork"),
		"frame": t("gearComponentListComponent.gearComponentFrame"),
	};

	return avatarMap[type];
}

export function getGearComponentAvatar(type) {
	const avatarMap = {
		"back_tire": "/src/assets/avatar/gearComponents/tire1.png",
		"front_tire": "/src/assets/avatar/gearComponents/tire1.png",
		"back_tube": "/src/assets/avatar/gearComponents/tube1.png",
		"front_tube": "/src/assets/avatar/gearComponents/tube1.png",
		"back_wheel_valve": "/src/assets/avatar/gearComponents/wheelValve1.png",
		"front_wheel_valve": "/src/assets/avatar/gearComponents/wheelValve1.png",
		"back_tubeless_sealant": "/src/assets/avatar/gearComponents/tubelessSealant1.png",
		"front_tubeless_sealant": "/src/assets/avatar/gearComponents/tubelessSealant1.png",
		"back_wheel": "/src/assets/avatar/gearComponents/wheel1.png",
		"front_wheel": "/src/assets/avatar/gearComponents/wheel1.png",
		"back_break_rotor": "/src/assets/avatar/gearComponents/diskBreakRotor1.png",
		"front_break_rotor": "/src/assets/avatar/gearComponents/diskBreakRotor1.png",
		"back_break_pads": "/src/assets/avatar/gearComponents/backBreakPads1.png",
		"front_break_pads": "/src/assets/avatar/gearComponents/backBreakPads1.png",
		"back_break_oil": "/src/assets/avatar/gearComponents/backBreakOil1.png",
		"front_break_oil": "/src/assets/avatar/gearComponents/backBreakOil1.png",
		"crank_left_power_meter": "/src/assets/avatar/gearComponents/crankPowerMeter1.png",
		"crank_right_power_meter": "/src/assets/avatar/gearComponents/crankPowerMeter1.png",
		"crankset_power_meter": "/src/assets/avatar/gearComponents/crankPowerMeter1.png",
		"pedals_left_power_meter": "/src/assets/avatar/gearComponents/pedalPowerMeter1.png",
		"pedals_right_power_meter": "/src/assets/avatar/gearComponents/pedalPowerMeter1.png",
		"pedals_power_meter": "/src/assets/avatar/gearComponents/pedalPowerMeter1.png",
		"pedals": "/src/assets/avatar/gearComponents/pedals1.png",
		"crankset": "/src/assets/avatar/gearComponents/crankset1.png",
		"cassette": "/src/assets/avatar/gearComponents/cassette1.png",
		"chain": "/src/assets/avatar/gearComponents/chain1.png",
		"front_shifter": "/src/assets/avatar/gearComponents/shifter1.png",
		"front_derailleur": "/src/assets/avatar/gearComponents/frontDerailleur1.png",
		"front_shifter": "/src/assets/avatar/gearComponents/shifter1.png",
		"front_derailleur": "/src/assets/avatar/gearComponents/rearDerailleur1.png",
		"bottom_bracket": "/src/assets/avatar/gearComponents/bottomBracket1.png",
		"bottle_cage": "/src/assets/avatar/gearComponents/bottleCage1.png",
		"handlebar": "/src/assets/avatar/gearComponents/handlebar1.png",
		"headset": "/src/assets/avatar/gearComponents/headset1.png",
		"computer_mount": "/src/assets/avatar/gearComponents/computerMount1.png",
		"handlebar_tape": "/src/assets/avatar/gearComponents/handlebarTape1.png",
		"grips": "/src/assets/avatar/gearComponents/grips1.png",
		"stem": "/src/assets/avatar/gearComponents/stem1.png",
		"seatpost": "/src/assets/avatar/gearComponents/seatpost1.png",
		"saddle": "/src/assets/avatar/gearComponents/saddle1.png",
		"fork": "/src/assets/avatar/gearComponents/fork1.png",
		"frame": "/src/assets/avatar/gearComponents/frame1.png",
	};

	return avatarMap[type];
}